// Central registry of all keyboard shortcuts
window.__shortcutsRegistry = [
  { chord: 'j', desc: 'Scroll down', category: 'Scrolling' },
  { chord: 'k', desc: 'Scroll up', category: 'Scrolling' },
  { chord: '{', desc: 'Previous heading', category: 'Scrolling' },
  { chord: '}', desc: 'Next heading', category: 'Scrolling' },
  { chord: 'gg', desc: 'Top of page', category: 'Scrolling' },
  { chord: 'G', desc: 'Bottom of page', category: 'Scrolling' },
  { chord: 'l', desc: 'Highlight active line', category: 'Scrolling' },
  { chord: 'Enter', desc: 'Open highlighted link', category: 'Scrolling' },
  { chord: 'h', desc: 'Home page', category: 'Navigation' },
  { chord: 'a', desc: 'About page', category: 'Navigation' },
  { chord: 'd', desc: 'Digital garden', category: 'Navigation' },
  { chord: 'c', desc: 'Credits page', category: 'Navigation' },
  { chord: '8', desc: 'Tags page', category: 'Navigation' },
  { chord: 's', desc: 'Settings page', category: 'Navigation' },
  { chord: 'r', desc: 'Resume', category: 'Navigation' },
  { chord: 'f', desc: 'RSS feed', category: 'Navigation' },
  { chord: 'em', desc: 'Email', category: 'Navigation' },
  { chord: 'li', desc: 'LinkedIn', category: 'Navigation' },
  { chord: 'gh', desc: 'GitHub', category: 'Navigation' },
  { chord: 'gl', desc: 'GitLab', category: 'Navigation' },
  { chord: 'b', desc: 'Codeberg', category: 'Navigation' },
  { chord: 'gr', desc: 'Gravatar', category: 'Navigation' },
  { chord: '<', desc: 'History back', category: 'Navigation' },
  { chord: '>', desc: 'History forward', category: 'Navigation' },
  { chord: 't', desc: 'Toggle theme', category: 'Toggles' },
  { chord: '9', desc: 'Toggle table of contents', category: 'Toggles' },
  { chord: 'f', desc: 'Search site', category: 'Toggles' },
  { chord: ':', desc: 'Command mode', category: 'Toggles' },
  { chord: 'ctrl+p', desc: 'Command mode', category: 'Toggles' },
  { chord: '?', desc: 'Show shortcuts popup', category: 'Toggles' },
  { chord: 'Esc', desc: 'Close popup / Cancel', category: 'Toggles' },
];
